Tree changed
Solar-Gators/docs pull request #16
Opened 2020-08-18 17:31 UTC by scuervo101

Added in subsections for mechanical, aero-body, and electrical. Added the sub teams to each subsection

2020-08-18 17:52 UTC, John-Carr requested changes
We should change the onboarding to a general what you need to do like join the slack. And add a specific onboarding for each team. Maintain website, and how to develop should be moved under electrical. The tree looks good I did not see any issues.
![image](https://user-images.githubusercontent.com/44035338/90547730-f5c6b200-e159-11ea-9c51-d311184d6a87.png)
(keep an onboarding there and add one for each team)

2020-08-29 16:20 UTC, Seth10001 approved these changes
This looks good to me now, you addressed the issues John mentioned.

2020-08-29 21:43 UTC, John-Carr approved these changes

2020-08-29 21:43 UTC, John-Carr commented
@scuervo101 Good to merge

2020-08-29 23:24 UTC, merged